// GENERATED by scripts/build-sanity-schema.mjs — do not edit by hand.
//
// Drop this folder into a Sanity Studio project and reference it from
// sanity.config.ts:
//
//   import { schemaTypes } from "./schema";
//   export default defineConfig({ /* ... */ schema: { types: schemaTypes } });
import messages_home from "./messages_home";
import messages_howItWorks from "./messages_howItWorks";
import messages_about from "./messages_about";
import messages_impact from "./messages_impact";
import messages_safeher from "./messages_safeher";
import messages_regions from "./messages_regions";
import messages_faq from "./messages_faq";
import messages_media from "./messages_media";

export const schemaTypes = [
  messages_home,
  messages_howItWorks,
  messages_about,
  messages_impact,
  messages_safeher,
  messages_regions,
  messages_faq,
  messages_media,
];
