// GENERATED by scripts/build-sanity-schema.mjs — do not edit by hand.
//
// Mirrors the "impact" namespace of content/messages/en/. Re-run the
// generator after adding or removing a key there, or the Studio and the site
// will disagree about what exists.
import { defineType } from "sanity";

export default defineType({
    name: "messages_impact",
    title: "Content — Impact",
    type: "document",
    fields: [
      {
        name: "namespace",
        title: "Namespace",
        type: "string",
        readOnly: true,
        initialValue: "impact",
        hidden: true
      },
      {
        name: "locale",
        title: "Language",
        type: "string",
        options: {
          list: [
            {
              title: "English",
              value: "en"
            },
            {
              title: "Français",
              value: "fr"
            }
          ]
        },
        validation: (Rule) => Rule.required()
      },
      {
        name: "content",
        title: "Content",
        type: "object",
        fields: [
          {
            name: "meta",
            title: "Meta",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "title",
                title: "Title",
                type: "string"
              },
              {
                name: "description",
                title: "Description",
                type: "text"
              }
            ]
          },
          {
            name: "hero",
            title: "Hero",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "eyebrow",
                title: "Eyebrow",
                type: "string"
              },
              {
                name: "title",
                title: "Title",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              }
            ]
          },
          {
            name: "preLaunch",
            title: "Pre Launch",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "bodyWithDate",
                title: "Body With Date",
                type: "text"
              },
              {
                name: "bodyWithoutDate",
                title: "Body Without Date",
                type: "string"
              },
              {
                name: "reason",
                title: "Reason",
                type: "text"
              },
              {
                name: "targetsHeading",
                title: "Targets Heading",
                type: "string"
              },
              {
                name: "targetLabel",
                title: "Target Label",
                type: "string"
              },
              {
                name: "targets",
                title: "Targets",
                type: "array",
                of: [
                  {
                    type: "object",
                    name: "targetsItem",
                    fields: [
                      {
                        name: "value",
                        title: "Value",
                        type: "string"
                      },
                      {
                        name: "label",
                        title: "Label",
                        type: "string"
                      }
                    ],
                    preview: {
                      select: {
                        title: "label"
                      }
                    }
                  }
                ]
              },
              {
                name: "targetsNote",
                title: "Targets Note",
                type: "text"
              }
            ]
          },
          {
            name: "unavailable",
            title: "Unavailable",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "body",
                title: "Body",
                type: "text"
              }
            ]
          },
          {
            name: "live",
            title: "Live",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "updatedLabel",
                title: "Updated Label",
                type: "string"
              },
              {
                name: "notAvailableLabel",
                title: "Not Available Label",
                type: "string"
              }
            ]
          },
          {
            name: "metrics",
            title: "Metrics",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "girlsReached",
                title: "Girls Reached",
                type: "object",
                options: {
                  collapsible: true,
                  collapsed: true
                },
                fields: [
                  {
                    name: "label",
                    title: "Label",
                    type: "string"
                  },
                  {
                    name: "help",
                    title: "Help",
                    type: "string"
                  }
                ]
              },
              {
                name: "conversationsManaged",
                title: "Conversations Managed",
                type: "object",
                options: {
                  collapsible: true,
                  collapsed: true
                },
                fields: [
                  {
                    name: "label",
                    title: "Label",
                    type: "string"
                  },
                  {
                    name: "help",
                    title: "Help",
                    type: "string"
                  }
                ]
              },
              {
                name: "activePartners",
                title: "Active Partners",
                type: "object",
                options: {
                  collapsible: true,
                  collapsed: true
                },
                fields: [
                  {
                    name: "label",
                    title: "Label",
                    type: "string"
                  },
                  {
                    name: "help",
                    title: "Help",
                    type: "string"
                  }
                ]
              }
            ]
          },
          {
            name: "privacy",
            title: "Privacy",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "points",
                title: "Points",
                type: "array",
                of: [
                  {
                    type: "object",
                    name: "pointsItem",
                    fields: [
                      {
                        name: "title",
                        title: "Title",
                        type: "string"
                      },
                      {
                        name: "body",
                        title: "Body",
                        type: "text"
                      }
                    ],
                    preview: {
                      select: {
                        title: "title"
                      }
                    }
                  }
                ]
              },
              {
                name: "policyLink",
                title: "Policy Link",
                type: "string"
              }
            ]
          },
          {
            name: "closing",
            title: "Closing",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "body",
                title: "Body",
                type: "string"
              },
              {
                name: "cta",
                title: "Cta",
                type: "string"
              }
            ]
          }
        ]
      }
    ],
    preview: {
      select: {
        locale: "locale"
      },
      prepare: ({ locale }: { locale?: string }) => ({
        title: "Impact",
        subtitle: locale === "fr" ? "Français" : "English",
      })
    }
  });
