// GENERATED by scripts/build-sanity-schema.mjs — do not edit by hand.
//
// Mirrors the "faq" namespace of content/messages/en/. Re-run the
// generator after adding or removing a key there, or the Studio and the site
// will disagree about what exists.
import { defineType } from "sanity";

export default defineType({
    name: "messages_faq",
    title: "Content — Faq",
    type: "document",
    fields: [
      {
        name: "namespace",
        title: "Namespace",
        type: "string",
        readOnly: true,
        initialValue: "faq",
        hidden: true
      },
      {
        name: "locale",
        title: "Language",
        type: "string",
        options: {
          list: [
            {
              title: "English",
              value: "en"
            },
            {
              title: "Français",
              value: "fr"
            }
          ]
        },
        validation: (Rule) => Rule.required()
      },
      {
        name: "content",
        title: "Content",
        type: "object",
        fields: [
          {
            name: "meta",
            title: "Meta",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "title",
                title: "Title",
                type: "string"
              },
              {
                name: "description",
                title: "Description",
                type: "text"
              }
            ]
          },
          {
            name: "hero",
            title: "Hero",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "eyebrow",
                title: "Eyebrow",
                type: "string"
              },
              {
                name: "title",
                title: "Title",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              }
            ]
          },
          {
            name: "sections",
            title: "Sections",
            type: "array",
            of: [
              {
                type: "object",
                name: "sectionsItem",
                fields: [
                  {
                    name: "heading",
                    title: "Heading",
                    type: "string"
                  },
                  {
                    name: "items",
                    title: "Items",
                    type: "array",
                    of: [
                      {
                        type: "object",
                        name: "itemsItem",
                        fields: [
                          {
                            name: "question",
                            title: "Question",
                            type: "string"
                          },
                          {
                            name: "answer",
                            title: "Answer",
                            type: "text"
                          }
                        ],
                        preview: {
                          select: {
                            title: "question"
                          }
                        }
                      }
                    ]
                  }
                ],
                preview: {
                  select: {
                    title: "heading"
                  }
                }
              }
            ]
          },
          {
            name: "closing",
            title: "Closing",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "body",
                title: "Body",
                type: "text"
              },
              {
                name: "cta",
                title: "Cta",
                type: "string"
              }
            ]
          }
        ]
      }
    ],
    preview: {
      select: {
        locale: "locale"
      },
      prepare: ({ locale }: { locale?: string }) => ({
        title: "Faq",
        subtitle: locale === "fr" ? "Français" : "English",
      })
    }
  });
