// GENERATED by scripts/build-sanity-schema.mjs — do not edit by hand.
//
// Mirrors the "howItWorks" namespace of content/messages/en/. Re-run the
// generator after adding or removing a key there, or the Studio and the site
// will disagree about what exists.
import { defineType } from "sanity";

export default defineType({
    name: "messages_howItWorks",
    title: "Content — How It Works",
    type: "document",
    fields: [
      {
        name: "namespace",
        title: "Namespace",
        type: "string",
        readOnly: true,
        initialValue: "howItWorks",
        hidden: true
      },
      {
        name: "locale",
        title: "Language",
        type: "string",
        options: {
          list: [
            {
              title: "English",
              value: "en"
            },
            {
              title: "Français",
              value: "fr"
            }
          ]
        },
        validation: (Rule) => Rule.required()
      },
      {
        name: "content",
        title: "Content",
        type: "object",
        fields: [
          {
            name: "meta",
            title: "Meta",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "title",
                title: "Title",
                type: "string"
              },
              {
                name: "description",
                title: "Description",
                type: "text"
              }
            ]
          },
          {
            name: "hero",
            title: "Hero",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "eyebrow",
                title: "Eyebrow",
                type: "string"
              },
              {
                name: "title",
                title: "Title",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              }
            ]
          },
          {
            name: "steps",
            title: "Steps",
            type: "array",
            of: [
              {
                type: "object",
                name: "stepsItem",
                fields: [
                  {
                    name: "number",
                    title: "Number",
                    type: "string"
                  },
                  {
                    name: "title",
                    title: "Title",
                    type: "string"
                  },
                  {
                    name: "body",
                    title: "Body",
                    type: "text"
                  },
                  {
                    name: "detail",
                    title: "Detail",
                    type: "text"
                  }
                ],
                preview: {
                  select: {
                    title: "title"
                  }
                }
              }
            ]
          },
          {
            name: "redFlag",
            title: "Red Flag",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              },
              {
                name: "layers",
                title: "Layers",
                type: "array",
                of: [
                  {
                    type: "object",
                    name: "layersItem",
                    fields: [
                      {
                        name: "title",
                        title: "Title",
                        type: "string"
                      },
                      {
                        name: "body",
                        title: "Body",
                        type: "text"
                      }
                    ],
                    preview: {
                      select: {
                        title: "title"
                      }
                    }
                  }
                ]
              },
              {
                name: "honesty",
                title: "Honesty",
                type: "text"
              }
            ]
          },
          {
            name: "limits",
            title: "Limits",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "items",
                title: "Items",
                type: "array",
                of: [
                  {
                    type: "text"
                  }
                ]
              },
              {
                name: "cta",
                title: "Cta",
                type: "string"
              }
            ]
          },
          {
            name: "finalCta",
            title: "Final Cta",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "body",
                title: "Body",
                type: "string"
              }
            ]
          }
        ]
      }
    ],
    preview: {
      select: {
        locale: "locale"
      },
      prepare: ({ locale }: { locale?: string }) => ({
        title: "How It Works",
        subtitle: locale === "fr" ? "Français" : "English",
      })
    }
  });
