// GENERATED by scripts/build-sanity-schema.mjs — do not edit by hand.
//
// Mirrors the "safeher" namespace of content/messages/en/. Re-run the
// generator after adding or removing a key there, or the Studio and the site
// will disagree about what exists.
import { defineType } from "sanity";

export default defineType({
    name: "messages_safeher",
    title: "Content — Safeher",
    type: "document",
    fields: [
      {
        name: "namespace",
        title: "Namespace",
        type: "string",
        readOnly: true,
        initialValue: "safeher",
        hidden: true
      },
      {
        name: "locale",
        title: "Language",
        type: "string",
        options: {
          list: [
            {
              title: "English",
              value: "en"
            },
            {
              title: "Français",
              value: "fr"
            }
          ]
        },
        validation: (Rule) => Rule.required()
      },
      {
        name: "content",
        title: "Content",
        type: "object",
        fields: [
          {
            name: "meta",
            title: "Meta",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "title",
                title: "Title",
                type: "string"
              },
              {
                name: "description",
                title: "Description",
                type: "text"
              }
            ]
          },
          {
            name: "hero",
            title: "Hero",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "eyebrow",
                title: "Eyebrow",
                type: "string"
              },
              {
                name: "title",
                title: "Title",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              }
            ]
          },
          {
            name: "whatIsIt",
            title: "What Is It",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              },
              {
                name: "points",
                title: "Points",
                type: "array",
                of: [
                  {
                    type: "object",
                    name: "pointsItem",
                    fields: [
                      {
                        name: "title",
                        title: "Title",
                        type: "string"
                      },
                      {
                        name: "body",
                        title: "Body",
                        type: "text"
                      }
                    ],
                    preview: {
                      select: {
                        title: "title"
                      }
                    }
                  }
                ]
              }
            ]
          },
          {
            name: "verification",
            title: "Verification",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              },
              {
                name: "steps",
                title: "Steps",
                type: "array",
                of: [
                  {
                    type: "object",
                    name: "stepsItem",
                    fields: [
                      {
                        name: "title",
                        title: "Title",
                        type: "string"
                      },
                      {
                        name: "body",
                        title: "Body",
                        type: "text"
                      }
                    ],
                    preview: {
                      select: {
                        title: "title"
                      }
                    }
                  }
                ]
              }
            ]
          },
          {
            name: "howReferralWorks",
            title: "How Referral Works",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "body",
                title: "Body",
                type: "text"
              },
              {
                name: "privacy",
                title: "Privacy",
                type: "text"
              },
              {
                name: "cta",
                title: "Cta",
                type: "string"
              }
            ]
          },
          {
            name: "directory",
            title: "Directory",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              },
              {
                name: "emptyLabel",
                title: "Empty Label",
                type: "string"
              },
              {
                name: "emptyBody",
                title: "Empty Body",
                type: "text"
              },
              {
                name: "targetNote",
                title: "Target Note",
                type: "text"
              },
              {
                name: "locationHeading",
                title: "Location Heading",
                type: "string"
              },
              {
                name: "locationBody",
                title: "Location Body",
                type: "text"
              }
            ]
          },
          {
            name: "forPartners",
            title: "For Partners",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "joinHeading",
                title: "Join Heading",
                type: "string"
              },
              {
                name: "joinBody",
                title: "Join Body",
                type: "text"
              },
              {
                name: "joinCta",
                title: "Join Cta",
                type: "string"
              },
              {
                name: "loginHeading",
                title: "Login Heading",
                type: "string"
              },
              {
                name: "loginBody",
                title: "Login Body",
                type: "string"
              },
              {
                name: "loginCta",
                title: "Login Cta",
                type: "string"
              }
            ]
          }
        ]
      }
    ],
    preview: {
      select: {
        locale: "locale"
      },
      prepare: ({ locale }: { locale?: string }) => ({
        title: "Safeher",
        subtitle: locale === "fr" ? "Français" : "English",
      })
    }
  });
