// GENERATED by scripts/build-sanity-schema.mjs — do not edit by hand.
//
// Mirrors the "about" namespace of content/messages/en/. Re-run the
// generator after adding or removing a key there, or the Studio and the site
// will disagree about what exists.
import { defineType } from "sanity";

export default defineType({
    name: "messages_about",
    title: "Content — About",
    type: "document",
    fields: [
      {
        name: "namespace",
        title: "Namespace",
        type: "string",
        readOnly: true,
        initialValue: "about",
        hidden: true
      },
      {
        name: "locale",
        title: "Language",
        type: "string",
        options: {
          list: [
            {
              title: "English",
              value: "en"
            },
            {
              title: "Français",
              value: "fr"
            }
          ]
        },
        validation: (Rule) => Rule.required()
      },
      {
        name: "content",
        title: "Content",
        type: "object",
        fields: [
          {
            name: "meta",
            title: "Meta",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "title",
                title: "Title",
                type: "string"
              },
              {
                name: "description",
                title: "Description",
                type: "text"
              }
            ]
          },
          {
            name: "hero",
            title: "Hero",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "eyebrow",
                title: "Eyebrow",
                type: "string"
              },
              {
                name: "title",
                title: "Title",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              }
            ]
          },
          {
            name: "origin",
            title: "Origin",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "body",
                title: "Body",
                type: "array",
                of: [
                  {
                    type: "text"
                  }
                ]
              }
            ]
          },
          {
            name: "problem",
            title: "Problem",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              },
              {
                name: "statistic",
                title: "Statistic",
                type: "object",
                options: {
                  collapsible: true,
                  collapsed: true
                },
                fields: [
                  {
                    name: "value",
                    title: "Value",
                    type: "string"
                  },
                  {
                    name: "label",
                    title: "Label",
                    type: "string"
                  },
                  {
                    name: "source",
                    title: "Source",
                    type: "text"
                  }
                ]
              },
              {
                name: "body",
                title: "Body",
                type: "array",
                of: [
                  {
                    type: "text"
                  }
                ]
              }
            ]
          },
          {
            name: "whyWhatsApp",
            title: "Why Whats App",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              },
              {
                name: "reasons",
                title: "Reasons",
                type: "array",
                of: [
                  {
                    type: "object",
                    name: "reasonsItem",
                    fields: [
                      {
                        name: "title",
                        title: "Title",
                        type: "string"
                      },
                      {
                        name: "body",
                        title: "Body",
                        type: "text"
                      }
                    ],
                    preview: {
                      select: {
                        title: "title"
                      }
                    }
                  }
                ]
              }
            ]
          },
          {
            name: "approach",
            title: "Approach",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              },
              {
                name: "points",
                title: "Points",
                type: "array",
                of: [
                  {
                    type: "object",
                    name: "pointsItem",
                    fields: [
                      {
                        name: "title",
                        title: "Title",
                        type: "string"
                      },
                      {
                        name: "body",
                        title: "Body",
                        type: "text"
                      }
                    ],
                    preview: {
                      select: {
                        title: "title"
                      }
                    }
                  }
                ]
              }
            ]
          },
          {
            name: "who",
            title: "Who",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              },
              {
                name: "groups",
                title: "Groups",
                type: "array",
                of: [
                  {
                    type: "text"
                  }
                ]
              },
              {
                name: "inclusion",
                title: "Inclusion",
                type: "text"
              }
            ]
          },
          {
            name: "partners",
            title: "Partners",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "body",
                title: "Body",
                type: "text"
              },
              {
                name: "accountability",
                title: "Accountability",
                type: "text"
              }
            ]
          },
          {
            name: "closing",
            title: "Closing",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "body",
                title: "Body",
                type: "text"
              }
            ]
          }
        ]
      }
    ],
    preview: {
      select: {
        locale: "locale"
      },
      prepare: ({ locale }: { locale?: string }) => ({
        title: "About",
        subtitle: locale === "fr" ? "Français" : "English",
      })
    }
  });
