// GENERATED by scripts/build-sanity-schema.mjs — do not edit by hand.
//
// Mirrors the "home" namespace of content/messages/en/. Re-run the
// generator after adding or removing a key there, or the Studio and the site
// will disagree about what exists.
import { defineType } from "sanity";

export default defineType({
    name: "messages_home",
    title: "Content — Home",
    type: "document",
    fields: [
      {
        name: "namespace",
        title: "Namespace",
        type: "string",
        readOnly: true,
        initialValue: "home",
        hidden: true
      },
      {
        name: "locale",
        title: "Language",
        type: "string",
        options: {
          list: [
            {
              title: "English",
              value: "en"
            },
            {
              title: "Français",
              value: "fr"
            }
          ]
        },
        validation: (Rule) => Rule.required()
      },
      {
        name: "content",
        title: "Content",
        type: "object",
        fields: [
          {
            name: "meta",
            title: "Meta",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "title",
                title: "Title",
                type: "string"
              },
              {
                name: "description",
                title: "Description",
                type: "text"
              }
            ]
          },
          {
            name: "hero",
            title: "Hero",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "trustHeadline",
                title: "Trust Headline",
                type: "string"
              },
              {
                name: "supporting",
                title: "Supporting",
                type: "text"
              },
              {
                name: "mission",
                title: "Mission",
                type: "text"
              },
              {
                name: "conversationLabel",
                title: "Conversation Label",
                type: "string"
              },
              {
                name: "conversationDisclaimer",
                title: "Conversation Disclaimer",
                type: "string"
              },
              {
                name: "conversation",
                title: "Conversation",
                type: "array",
                of: [
                  {
                    type: "object",
                    name: "conversationItem",
                    fields: [
                      {
                        name: "from",
                        title: "From",
                        type: "string"
                      },
                      {
                        name: "text",
                        title: "Text",
                        type: "string"
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            name: "anonymity",
            title: "Anonymity",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "body",
                title: "Body",
                type: "text"
              },
              {
                name: "points",
                title: "Points",
                type: "array",
                of: [
                  {
                    type: "object",
                    name: "pointsItem",
                    fields: [
                      {
                        name: "title",
                        title: "Title",
                        type: "string"
                      },
                      {
                        name: "body",
                        title: "Body",
                        type: "string"
                      }
                    ],
                    preview: {
                      select: {
                        title: "title"
                      }
                    }
                  }
                ]
              },
              {
                name: "note",
                title: "Note",
                type: "string"
              },
              {
                name: "writeHowYouLike",
                title: "Write How You Like",
                type: "text"
              }
            ]
          },
          {
            name: "process",
            title: "Process",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              },
              {
                name: "steps",
                title: "Steps",
                type: "array",
                of: [
                  {
                    type: "object",
                    name: "stepsItem",
                    fields: [
                      {
                        name: "title",
                        title: "Title",
                        type: "string"
                      },
                      {
                        name: "body",
                        title: "Body",
                        type: "text"
                      }
                    ],
                    preview: {
                      select: {
                        title: "title"
                      }
                    }
                  }
                ]
              },
              {
                name: "cta",
                title: "Cta",
                type: "string"
              }
            ]
          },
          {
            name: "trust",
            title: "Trust",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "cards",
                title: "Cards",
                type: "array",
                of: [
                  {
                    type: "object",
                    name: "cardsItem",
                    fields: [
                      {
                        name: "title",
                        title: "Title",
                        type: "string"
                      },
                      {
                        name: "body",
                        title: "Body",
                        type: "text"
                      }
                    ],
                    preview: {
                      select: {
                        title: "title"
                      }
                    }
                  }
                ]
              }
            ]
          },
          {
            name: "impact",
            title: "Impact",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              },
              {
                name: "targetLabel",
                title: "Target Label",
                type: "string"
              },
              {
                name: "targets",
                title: "Targets",
                type: "array",
                of: [
                  {
                    type: "object",
                    name: "targetsItem",
                    fields: [
                      {
                        name: "value",
                        title: "Value",
                        type: "string"
                      },
                      {
                        name: "label",
                        title: "Label",
                        type: "string"
                      }
                    ],
                    preview: {
                      select: {
                        title: "label"
                      }
                    }
                  }
                ]
              },
              {
                name: "note",
                title: "Note",
                type: "text"
              },
              {
                name: "liveHeading",
                title: "Live Heading",
                type: "string"
              },
              {
                name: "cta",
                title: "Cta",
                type: "string"
              }
            ]
          },
          {
            name: "finalCta",
            title: "Final Cta",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "body",
                title: "Body",
                type: "string"
              },
              {
                name: "reassurance",
                title: "Reassurance",
                type: "string"
              }
            ]
          }
        ]
      }
    ],
    preview: {
      select: {
        locale: "locale"
      },
      prepare: ({ locale }: { locale?: string }) => ({
        title: "Home",
        subtitle: locale === "fr" ? "Français" : "English",
      })
    }
  });
