// GENERATED by scripts/build-sanity-schema.mjs — do not edit by hand.
//
// Mirrors the "regions" namespace of content/messages/en/. Re-run the
// generator after adding or removing a key there, or the Studio and the site
// will disagree about what exists.
import { defineType } from "sanity";

export default defineType({
    name: "messages_regions",
    title: "Content — Regions",
    type: "document",
    fields: [
      {
        name: "namespace",
        title: "Namespace",
        type: "string",
        readOnly: true,
        initialValue: "regions",
        hidden: true
      },
      {
        name: "locale",
        title: "Language",
        type: "string",
        options: {
          list: [
            {
              title: "English",
              value: "en"
            },
            {
              title: "Français",
              value: "fr"
            }
          ]
        },
        validation: (Rule) => Rule.required()
      },
      {
        name: "content",
        title: "Content",
        type: "object",
        fields: [
          {
            name: "northern",
            title: "Northern",
            type: "string"
          },
          {
            name: "upperEast",
            title: "Upper East",
            type: "string"
          },
          {
            name: "upperWest",
            title: "Upper West",
            type: "string"
          }
        ]
      }
    ],
    preview: {
      select: {
        locale: "locale"
      },
      prepare: ({ locale }: { locale?: string }) => ({
        title: "Regions",
        subtitle: locale === "fr" ? "Français" : "English",
      })
    }
  });
