// GENERATED by scripts/build-sanity-schema.mjs — do not edit by hand.
//
// Mirrors the "media" namespace of content/messages/en/. Re-run the
// generator after adding or removing a key there, or the Studio and the site
// will disagree about what exists.
import { defineType } from "sanity";

export default defineType({
    name: "messages_media",
    title: "Content — Media",
    type: "document",
    fields: [
      {
        name: "namespace",
        title: "Namespace",
        type: "string",
        readOnly: true,
        initialValue: "media",
        hidden: true
      },
      {
        name: "locale",
        title: "Language",
        type: "string",
        options: {
          list: [
            {
              title: "English",
              value: "en"
            },
            {
              title: "Français",
              value: "fr"
            }
          ]
        },
        validation: (Rule) => Rule.required()
      },
      {
        name: "content",
        title: "Content",
        type: "object",
        fields: [
          {
            name: "meta",
            title: "Meta",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "title",
                title: "Title",
                type: "string"
              },
              {
                name: "description",
                title: "Description",
                type: "text"
              }
            ]
          },
          {
            name: "hero",
            title: "Hero",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "eyebrow",
                title: "Eyebrow",
                type: "string"
              },
              {
                name: "title",
                title: "Title",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              }
            ]
          },
          {
            name: "contact",
            title: "Contact",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "body",
                title: "Body",
                type: "string"
              },
              {
                name: "responseNote",
                title: "Response Note",
                type: "string"
              }
            ]
          },
          {
            name: "facts",
            title: "Facts",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "text"
              },
              {
                name: "items",
                title: "Items",
                type: "array",
                of: [
                  {
                    type: "object",
                    name: "itemsItem",
                    fields: [
                      {
                        name: "label",
                        title: "Label",
                        type: "string"
                      },
                      {
                        name: "value",
                        title: "Value",
                        type: "text"
                      }
                    ],
                    preview: {
                      select: {
                        title: "label"
                      }
                    }
                  }
                ]
              }
            ]
          },
          {
            name: "reporting",
            title: "Reporting",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "intro",
                title: "Intro",
                type: "string"
              },
              {
                name: "points",
                title: "Points",
                type: "array",
                of: [
                  {
                    type: "object",
                    name: "pointsItem",
                    fields: [
                      {
                        name: "title",
                        title: "Title",
                        type: "string"
                      },
                      {
                        name: "body",
                        title: "Body",
                        type: "text"
                      }
                    ],
                    preview: {
                      select: {
                        title: "title"
                      }
                    }
                  }
                ]
              }
            ]
          },
          {
            name: "assets",
            title: "Assets",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "body",
                title: "Body",
                type: "string"
              },
              {
                name: "logoHeading",
                title: "Logo Heading",
                type: "string"
              },
              {
                name: "logoBody",
                title: "Logo Body",
                type: "text"
              },
              {
                name: "pendingLabel",
                title: "Pending Label",
                type: "string"
              },
              {
                name: "pendingBody",
                title: "Pending Body",
                type: "text"
              },
              {
                name: "colourHeading",
                title: "Colour Heading",
                type: "string"
              },
              {
                name: "colourNote",
                title: "Colour Note",
                type: "text"
              }
            ]
          },
          {
            name: "coverage",
            title: "Coverage",
            type: "object",
            options: {
              collapsible: true,
              collapsed: true
            },
            fields: [
              {
                name: "heading",
                title: "Heading",
                type: "string"
              },
              {
                name: "pendingHeading",
                title: "Pending Heading",
                type: "string"
              },
              {
                name: "pendingBody",
                title: "Pending Body",
                type: "text"
              },
              {
                name: "note",
                title: "Note",
                type: "text"
              }
            ]
          }
        ]
      }
    ],
    preview: {
      select: {
        locale: "locale"
      },
      prepare: ({ locale }: { locale?: string }) => ({
        title: "Media",
        subtitle: locale === "fr" ? "Français" : "English",
      })
    }
  });
